version: "2"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: >
      sh -c '
      mix phoenix.server
      '
    working_dir: /app
    ports:
      - '4000:4000'
    links:
      - postgres
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/deps
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
